<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/14 23:06:09
?>
<?php echo form_tag('type/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($type, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('type[name]', __($labels['type{name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('type{name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('type{name}')): ?>
    <?php echo form_error('type{name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($type, 'getName', array (
  'size' => 80,
  'control_name' => 'type[name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('type' => $type)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($type->getId()): ?>
<?php echo button_to(__('حذف'), 'type/delete?id='.$type->getId(), array (
  'post' => true,
  'confirm' => __('آیا مطمئن هستید ؟'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
