<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/14 23:06:09
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('فهرست نوع مستندات'), 'type/list?id='.$type->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('ذخیره'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('ذخیره و اضافه'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
