<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/14 19:46:42
?>

<ul class="sf_admin_actions">
  <li><?php echo button_to(__('طراحی نوع سند'), 'design/new', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>

