<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/14 19:46:42
?>
<table cellspacing="0" class="sf_admin_list" style="width: 50%">
<thead>
<tr>
<?php include_partial('list_th_tabular') ?>
 <th id="sf_admin_list_th_sf_actions" ><?php echo __('عملیات') ?></th>
</tr>
</thead>
<tfoot>
<tr><th colspan="3">
<div class="float-right">
<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/first.png', array('align' => 'absmiddle', 'alt' => __('اولین'), 'title' => __('اولین'))), 'type/list?page=1') ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/previous.png', array('align' => 'absmiddle', 'alt' => __('قبلی'), 'title' => __('قبلی'))), 'type/list?page='.$pager->getPreviousPage()) ?>

  <?php foreach ($pager->getLinks() as $page): ?>
    <?php echo link_to_unless($page == $pager->getPage(), $page, 'type/list?page='.$page) ?>
  <?php endforeach; ?>

  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/next.png', array('align' => 'absmiddle', 'alt' => __('بعدی'), 'title' => __('بعدی'))), 'type/list?page='.$pager->getNextPage()) ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/last.png', array('align' => 'absmiddle', 'alt' => __('آخرین'), 'title' => __('آخرین'))), 'type/list?page='.$pager->getLastPage()) ?>
<?php endif; ?>
</div>
<?php echo format_number_choice('[0] 0نتیجه|[1] 1 نتیجه|(1,+Inf] %1% نتیجه', array('%1%' => $pager->getNbResults()), $pager->getNbResults()) ?>

</th></tr>
</tfoot>
<tbody>
<?php $i = 1; foreach ($pager->getResults() as $type): $odd = fmod(++$i, 2) ?>
<tr class="sf_admin_row_<?php echo $odd ?>">
<?php include_partial('list_td_tabular', array('type' => $type)) ?>
<?php include_partial('list_td_actions', array('type' => $type)) ?>
</tr>
<?php endforeach; ?>
</tbody>
</table>
