<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/14 19:46:42
?>
  <th id="sf_admin_list_th_id" style="width: 100px;">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/type/sort') == 'id'): ?>
      <?php echo link_to(__('شماره'), 'type/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __(($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort'))== 'asc' ? 'صعودی' : 'نزولی') ?>)
      <?php else: ?>
      <?php echo link_to(__('شماره'), 'type/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_name" style="width: 250px;">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/type/sort') == 'name'): ?>
      <?php echo link_to(__('نام'), 'type/list?sort=name&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __(($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort'))== 'asc' ? 'صعودی' : 'نزولی') ?>)
      <?php else: ?>
      <?php echo link_to(__('نام'), 'type/list?sort=name&type=asc') ?>
      <?php endif; ?>
          </th>
