<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 06:00:26
?>
    <td><?php echo $user->getFirstName() ?></td>
      <td><?php echo $user->getLastName() ?></td>
      <td><?php echo link_to($user->getEmail() ? $user->getEmail() : __('-'), 'user/edit?id='.$user->getId()) ?></td>
    <td><?php echo $user->getMajor() ?></td>
      <td><?php echo $user->getLevel() ?></td>
      <td><?php echo $user->getPhone() ?></td>
      <td><?php echo $user->getCredential() ?></td>
      <td><?php echo $user->getNote() ?></td>
      <td><?php echo ($user->getCreatedAt() !== null && $user->getCreatedAt() !== '') ? format_date($user->getCreatedAt(), "f") : '' ?></td>
  