<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 06:00:26
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'user/edit?id='.$user->getId()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'user/delete?id='.$user->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
  <li><?php echo link_to(image_tag('frontend/default_icon.png', array('alt' => __('View documents'), 'title' => __('View documents'))), 'user/view?id='.$user->getId()) ?></li>
  <li><?php echo link_to(image_tag('frontend/user.png', array('alt' => __('View profile'), 'title' => __('View profile'))), 'user/profile?id='.$user->getId()) ?></li>
</ul>
</td>
