<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 06:00:26
?>
<td colspan="9">
    <?php echo $user->getFirstName() ?>
     - 
    <?php echo $user->getLastName() ?>
     - 
    <?php echo link_to($user->getEmail() ? $user->getEmail() : __('-'), 'user/edit?id='.$user->getId()) ?>
     - 
    <?php echo $user->getMajor() ?>
     - 
    <?php echo $user->getLevel() ?>
     - 
    <?php echo $user->getPhone() ?>
     - 
    <?php echo $user->getCredential() ?>
     - 
    <?php echo $user->getNote() ?>
     - 
    <?php echo ($user->getCreatedAt() !== null && $user->getCreatedAt() !== '') ? format_date($user->getCreatedAt(), "f") : '' ?>
     - 
</td>