<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 06:00:26
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('ویرایش مشخصات کاربر', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('user/edit_header', array('user' => $user)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('user/edit_messages', array('user' => $user, 'labels' => $labels)) ?>
<?php include_partial('user/edit_form', array('user' => $user, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('user/edit_footer', array('user' => $user)) ?>
</div>

</div>
