default:
  http_metas:
    content-type: text/html

  metas:
    title:        Document management
    robots:       index, follow
    description:  Document Repository System
    keywords:     document, repository
    language:     en

  stylesheets:    [main, document]

  javascripts:    [ document ]

  has_layout:     on
  layout:         document_layout
