<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 07:09:15
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('create'), 'type/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
