<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 07:09:15
?>
    <td><?php echo link_to($type->getId() ? $type->getId() : __('-'), 'type/edit?id='.$type->getId()) ?></td>
    <td><?php echo link_to($type->getName() ? $type->getName() : __('-'), 'type/edit?id='.$type->getId()) ?></td>
