<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 07:09:15
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/type/sort') == 'id'): ?>
      <?php echo link_to(__('شماره'), 'type/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('شماره'), 'type/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_name">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/type/sort') == 'name'): ?>
      <?php echo link_to(__('نام'), 'type/list?sort=name&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/type/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('نام'), 'type/list?sort=name&type=asc') ?>
      <?php endif; ?>
          </th>
