<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 07:09:15
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit type', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('type/edit_header', array('type' => $type)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('type/edit_messages', array('type' => $type, 'labels' => $labels)) ?>
<?php include_partial('type/edit_form', array('type' => $type, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('type/edit_footer', array('type' => $type)) ?>
</div>

</div>
