<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/11 08:51:24
?>

<ul class="sf_admin_actions">
  <li><?php echo button_to(__('فهرست کاربران'), 'user/list?id='.$user->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('ذخیره'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('ذخیره و اضافه'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
