<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/11 08:51:24
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('ایجاد کاربر'), 'user/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
