<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/11 08:51:24
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('ویرایش'), 'title' => __('ویرایش'))), 'user/edit?id='.$user->getId()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('حذف'), 'title' => __('حذف'))), 
				'user/delete?id='.$user->getId(), array (
  'post' => true,
  'confirm' => __('آیا مطمئن هستید ؟'),
)) ?></li>
  <li>
  <?php echo link_to(image_tag('frontend/default_icon.png', array('alt' => __('مشاهده اسناد'), 'title' => __('مشاهده اسناد'))), 'user/view?id='.$user->getId()) ?>
  </li>
  <li>
  <?php echo link_to(image_tag('frontend/user.png', array('alt' => __('مشاهده پروفایل'), 'title' => __('مشاهده پروفایل'))), 'user/profile?id='.$user->getId()) ?>
  </li>
</ul>
</td>
