<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/11 14:12:32
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<?php //echo __('ویرایش مشخصات کاربر', array()) ?>

<table style="width: 100%">
<tr><td>
	&nbsp;&nbsp;&nbsp;&nbsp;
	
<?php echo form_tag('user/save', array('id'=> 'sf_admin_edit_form',
'name' => 'sf_admin_edit_form','multipart' => true, )) ?>
	
	<?php include_partial('edit_actions', array('user' => $user)) ?>
	
</form >	
	</td>
	<td style="direction: ltr;">
	<ul class="sf_admin_actions">
	      <li class="float-left"><?php if ($user->getId()): ?>
	<?php echo button_to(__('حذف'), 'user/delete?id='.$user->getId(), array (
	  'post' => true,
	  'confirm' => __('آیا مطمئن هستید ؟'),
	  'class' => 'sf_admin_action_delete',
	)) ?><?php endif; ?>
	</li>
	  </ul>
	  </td>
</tr>
</table>

<div id="sf_admin_header">
<?php include_partial('user/edit_header', array('user' => $user)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('user/edit_messages', array('user' => $user, 'labels' => $labels)) ?>
<?php include_partial('user/edit_form', array('user' => $user, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('user/edit_footer', array('user' => $user)) ?>
</div>

</div>
