<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/09/15 06:39:01

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfEmailValidator_username'] = new sfEmailValidator();
  $validators['sfEmailValidator_username']->initialize($context, array (
  'strict' => true,
  'email_error' => 'پست الکترونیکی وارد شده صحیح نمی باشد.',
));
  $validators['sfStringValidator_password'] = new sfStringValidator();
  $validators['sfStringValidator_password']->initialize($context, array (
  'min' => 6,
  'min_error' => 'رمز وارد شده از 6 حرف کوتاه تر است.',
));
  $validatorManager->registerName('username', 1, 'برای ورود باید پست الکترونیکی خود را وارد نمایید.', null, null, false);
  $validatorManager->registerValidator('username', $validators['sfEmailValidator_username'], null);
  $validatorManager->registerName('password', 1, 'رمز خود را وارد نکرده اید.', null, null, false);
  $validatorManager->registerValidator('password', $validators['sfStringValidator_password'], null);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
