<?php
// auto-generated by sfViewConfigHandler
// date: 2009/09/15 06:39:01
$context  = $this->getContext();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('service_layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Document management', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Document Repository System', false, false);
  $response->addMeta('keywords', 'document, repository', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addStylesheet('service', '', array ());
  $response->addJavascript('document');


